# Generated by Django 4.1.7 on 2023-03-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonials')),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
