# Generated by Django 4.1.7 on 2023-03-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='herosection',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
