# Generated by Django 4.1.7 on 2023-04-02 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_altservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProjectsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OurProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='ourprojects')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('is_home', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ourprojectscategory')),
            ],
        ),
    ]
